### PR TITLE
make it usable as installable cmdline tool

### PR DESCRIPTION
**Pull request by asdfugil**
`npm i -g asdfugil/node-anime`

Tool will be available as command `node-anime`

also this does not seem to be licensed

### CODE REVIEW

**Comment by MeemeeLab** [comment]
This repository is licensed under Apache2.0 (Written in package.json), I'll add LICENSE file later

**Comment by MeemeeLab** [comment]
Looks like npm installable cmdline is working right without any code changes, And interface.js change causes error on windows.

**Comment by MeemeeLab** [comment]
I'm sorry, I was working on current directory that had package.json file...
Anyways, This was fixed by #7.

**Comment by asdfugil** [comment]
> Looks like npm installable cmdline is working right without any code changes, And interface.js change causes error on windows. I'll close this PR, but I'll publish this package to npm registry.

Make sure you are not testing inside of the source tree

**Comment by asdfugil** [comment]
Actually nevermind didn't see config.js

**Pull request closed without merging**
